bot:
  map: lost_time_1
buff_skill:
  cooldown:
  - 600
  keys:
  - '0'
directional_attack:
  cooldown: 0.07
  range_x: 300
  range_y: 150
edge_teleport:
  enable: false
email:
  enable: true
  receiver_email: zsp2233001@gmailcom
health_monitor:
  add_hp_cooldown: 0.3
  add_hp_percent: 40
  add_mp_percent: 20
  fps_limit: 10
  return_home_if_no_potion: true
key:
  add_hp: '4'
  add_mp: b
  aoe_skill: s
  directional_attack: a
  return_home: '8'
  teleport: space
monster_detect:
  search_box_margin: 30
nametag:
  mode: histogram_eq
route:
  search_range: 5
rune_detect:
  debug: true
rune_warning_cn:
  diff_thres: 0.3
scheduled_channel_switching:
  interval_seconds: 10
system:
  fps_limit_main: 15
watchdog:
  last_attack_timeout: 300
  last_attack_timeout_action: go_home
  timeout: 3
