bot:
  map: first_barrack
buff_skill:
  cooldown:
  - 290
  - 290
  - 240
  - 600
  keys:
  - '3'
  - '4'
  - '5'
  - '0'
channel_change:
  enable: true
  mode: 'true'
directional_attack:
  cooldown: 0.05
  range_x: 150
edge_teleport:
  enable: false
email:
  enable: true
  receiver_email: zsp2233001@gmailcom
game_window:
  size:
  - 708
  - 1298
health_monitor:
  add_hp_cooldown: 0.3
  add_hp_percent: 30
  add_mp_percent: 20
  force_heal: true
  fps_limit: 10
  return_home_if_no_potion: true
key:
  add_hp: s
  add_mp: b
  aoe_skill: r
  directional_attack: s
  jump: v
  return_home: '8'
  teleport: space
minimap:
  offset:
  - -30
  - -25
monster_detect:
  search_box_margin: 70
nametag:
  mode: histogram_eq
route:
  search_range: 5
rune_detect:
  debug: true
rune_warning_cn:
  diff_thres: 0.3
scheduled_channel_switching:
  interval_seconds: 3
system:
  fps_limit_main: 15
ui_coords:
  login_button_thres: 0.06
watchdog:
  last_attack_timeout: 600
  last_attack_timeout_action: go_home
  timeout: 3
