bot:
  map: garden_of_green_2
buff_skill:
  cooldown:
  - 45
  - 600
  - 160
  keys:
  - '9'
  - '0'
  - '3'
directional_attack:
  cooldown: 0.1
  range_x: 150
  range_y: 150
edge_teleport:
  enable: false
game_window:
  size:
  - 700
  - 1282
health_monitor:
  add_hp_cooldown: 0.3
  add_hp_percent: 40
  add_mp_percent: 20
  fps_limit: 10
  return_home_if_no_potion: true
key:
  add_hp: b
  add_mp: b
  aoe_skill: r
  directional_attack: r
  return_home: '8'
  teleport: space
monster_detect:
  search_box_margin: 30
nametag:
  mode: histogram_eq
route:
  search_range: 5
rune_detect:
  debug: true
rune_warning_cn:
  diff_thres: 0.3
system:
  fps_limit_main: 15
watchdog:
  last_attack_timeout: 300
  last_attack_timeout_action: go_home
  timeout: 3
