bot:
  map: north_forest_training_ground_8
directional_attack:
  cooldown: 0.1
  range_x: 300
  range_y: 150
edge_teleport:
  enable: false
game_window:
  size:
  - 759
  - 1282
health_monitor:
  add_hp_percent: 40
  add_mp_percent: 20
  fps_limit: 10
  return_home_if_no_potion: true
key:
  add_hp: b
  add_mp: b
  aoe_skill: s
  directional_attack: a
  jump: v
  return_home: '8'
  teleport: space
monster_detect:
  search_box_margin: 30
route:
  search_range: 5
rune_detect:
  debug: true
rune_warning_cn:
  diff_thres: 0.3
system:
  fps_limit_main: 15
watchdog:
  last_attack_timeout: 300
  timeout: 3
