bot:
  map: land_of_wild_boar
channel_change:
  enable: true
directional_attack:
  cooldown: 0.1
  range_x: 300
edge_teleport:
  enable: false
game_window:
  size:
  - 759
  - 1282
health_monitor:
  add_hp_percent: 40
  add_mp_percent: 20
  fps_limit: 10
  return_home_if_no_potion: true
key:
  add_hp: b
  add_mp: b
  aoe_skill: s
  directional_attack: s
  jump: v
  return_home: '8'
  teleport: space
minimap:
  offset:
  - -30
  - -29
monster_detect:
  diff_thres: 0.5
  mode: template_free
route:
  search_range: 5
rune_detect:
  debug: true
rune_warning_cn:
  diff_thres: 0.3
system:
  fps_limit_main: 15
watchdog:
  last_attack_timeout: 300
  timeout: 3
